swagger: "2.0"
info:
  title: "API 문서"
  description: "EastSunSecurity 백엔드 API 문서"
  version: "1.0"

definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      type:
        type: string
