openapi: 3.0.0
info:
  title: "API 문서"
  description: "ewha 백엔드 API 문서"
  version: "1.0"
tags:
  - name: "login"
    description: "타 api 실행전 로그인을 해야합니다."
  - name: "lecture"
    description: "강의 목록을 가져오는 api 입니다."

paths:
  /api/user/login:
    post:
      tags:
        - login
      summary: 교수 로그인
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - pw
              properties:
                email:
                  type: string
                  format: email
                pw:
                  type: string
                  format: password
            examples:
              professor:
                value:
                  email: "dev_professor@test.com"
                  pw: "1234"
              student:
                value:
                  email: "dev_student@test.com"
                  pw: "1234"

      responses:
        '200':
          description: Successful login
          headers:
            Set-Cookie:
              schema:
                type: string
                description: Authentication cookie for the user.
                example: "access_token_cookie=eyJ0eXAi...; Secure; HttpOnly; Path=/; SameSite=None"
          content:
            application/json:
              schema:
                type: object
                properties:
                  loginSuccess:
                    type: integer
                    description: Status indicating successful login. 1 for success.
                    example: 1
  /api/lecture/list:
    get:
      tags:
        - lecture
      summary: Retrieve a list of lectures
      operationId: getLectureList
      responses:
        '200':
          description: A list of lectures and user information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  lecturelist:
                    type: array
                    items:
                      $ref: '#/components/schemas/Lecture'
                  userInfo:
                    $ref: '#/components/schemas/UserInfo'
                  role:
                    type: integer
                    description: Role of the user.

components:
  securityScheme:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token_cookie
  schemas:
    Lecture:
      type: object
      properties:
        lecture_no:
          type: integer
        lecture_name:
          type: string
        year:
          type: string
          example: "2023"
        semester:
          type: string
          example: "1학기"
        major:
          type: string
          example: "한일통역"
        separated:
          type: string
          example: "1분반"
        professor:
          type: string
          example: "교수"
    
    UserInfo:
      type: object
      properties:
        type:
          type: string
          example: "login"
        user_no:
          type: integer
        user_email:
          type: string
          format: email
        user_name:
          type: string
        user_major:
          type: string
        user_perm:
          type: integer
